'\" t
.\"     Title: Empire
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 05/06/2017
.\"    Manual: Games
.\"    Source: empire
.\"  Language: English
.\"
.TH "EMPIRE" "6" "05/06/2017" "empire" "Games"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名前"
empire \- 世紀のウォーゲーム
.SH "書式"
.HP \w'\fBempire\fR\ 'u
\fBempire\fR [\-w\ \fIwater\fR] [\-s\ \fIsmooth\fR] [\-d\ \fIdelay\fR] [\-S\ \fIsave\-interval\fR] [\-f\ \fIsavefile\fR]
.SH "概要"
.PP
Empireはあなたとコンピュータの2人の皇帝による全面戦争のシミュレーションゲームです。 もちろん勝つのは1人で、ゲームの目的は相手を打ち負かすことです。 コンピュータとあなたは同じルールでプレーします。
.PP
\fB\-w\fR\fIwater\fR
.RS 4
このオプションはマップの水域の量を決定します。 指定した百分率(%)の値がマップの水域になります。デフォルトは70%です。
\fIwater\fRは10から90の間の整数でなければなりません。
.RE
.PP
\fB\-s\fR\fIsmooth\fR
.RS 4
このオプションはマップの滑らかさを決めます。 値が小さいと多くの小さな島や湖でできた混沌としたマップが作られ、 大きいと少数の大きな大陸のあるマップが作られます。 値が大きいほど生成に時間が掛かるので注意してください。 デフォルトは5です。
.RE
.PP
\fB\-d\fR\fIdelay\fR
.RS 4
このオプションは画面の上部にメッセージを表示した後にどのくらいの長さコンピュータが待つかを決めます。
\fIdelay\fRはミリ秒で指定します。 デフォルトは2000で、ユーザにはメッセージを読む時間が2秒間あります。
.RE
.SH "例"
.PP
empire \-w90 \-s2
.PP
これは多くの島のあるマップを生成します。
.PP
empire \-w50 \-s0
.PP
これはかなり変わったマップを生成します。 これは臆病者には勧められません。
.PP
empire \-w10
.PP
これは多くの島と少しの湖のあるマップを生成します。 このようなマップでは、コンピュータは無意味な輸送艦を多く作りがちで苦戦します。
.PP
これ以外にも2つのオプションがあります。
.PP
\fB\-S\fR\fIinterval\fR
.RS 4
ゲームの\fI保存間隔\fRを設定します(デフォルトは10)。
\fIinterval\fRターンに一度、あなたが動かした後にゲームの状態を保存します。 これにはモードを変えた場合や、コマンドモードでの`M\*(Aqや`N\*(Aqを含む様々な行動も含まれます。
.RE
.PP
\fB\-f\fR\fIsavefile\fR
.RS 4
保存ファイル名を設定します(通常はempsave\&.dat)。
.RE
.SH "はじめに"
.PP
Empireはあなたとコンピュータが対戦するウォーゲームです。 ゲームの世界は正方形で構成されていて、そこには都市、陸、水域があります。 都市では地上部隊、航空機、艦船を生産することができ、それで敵地を破壊、探索し、都市を占領します。 このゲームの目的は敵地を全て破壊し、全ての都市を奪うことです。
.PP
この世界は60\(mu100個の正方形で構成された長方形で、 海(\&.)、陸(+)、中立の都市(*)、コンピュータの都市(X)、そしてあなたの都市(O)が存在します。
.PP
マップはあなたの手番の間、画面に表示されます。 (端末の画面が小さい場合はマップの一部のみ表示されます。) 各ユニットはマップ上でそれぞれの文字として表示される。 いくつかの例外がありますが、1つのマスには1つのユニットしか存在できません。 マップは、あなたのユニットと接した8方向のマスのみ表示されます。 この情報はあなたの移動前と移動後に更新されます。 マップには最後に知られた情報が表示されています。
.PP
ゲームはあなたの都市1つとコンピュータの都市1つの状態から始まります。 都市では新しいユニットを生成できます。 あなたのそれぞれの都市では、コストに応じて望む種類の新しいユニットをさらに生成することができます。 多くのプレイヤーは特別に何かをするまではAutomove(移動モード)コマンドを使います。 それぞれのラウンドで、プレイヤーは自動的に行動しないユニットを動かすことを求められます。
.PP
マップの座標は4桁の数値で表します。 先頭の2桁は行で、後の2桁は列です。
.SH "ユニット"
.PP
ユニットには次のものがあります:
.TS
allbox center tab(:);
l c c r r r c
l c c r r r c
l c c r r r c
l c c r r r c
l c c r r r c
l c c r r r c
l c c r r r c
l c c r r r c
l c c r r r c
l c c r r r c.
T{
ユニット
T}:T{
あなた
T}:T{
相手
T}:T{
移動 (Moves)
T}:T{
ヒットポイント (Hits)
T}:T{
攻撃 (Str)
T}:T{
コスト (Cost)
T}
T{
地上部隊 (Army)
T}:T{
A
T}:T{
a
T}:T{
1
T}:T{
1
T}:T{
1
T}:T{
5(6)
T}
T{
戦闘機 (Fighter)
T}:T{
F
T}:T{
f
T}:T{
8
T}:T{
1
T}:T{
1
T}:T{
10(12)
T}
T{
哨戒艇 (Patrol Boat)
T}:T{
P
T}:T{
p
T}:T{
4
T}:T{
1
T}:T{
1
T}:T{
15(18)
T}
T{
駆逐艦 (Destroyer)
T}:T{
D
T}:T{
d
T}:T{
2
T}:T{
3
T}:T{
1
T}:T{
20(24)
T}
T{
潜水艦 (Submarine)
T}:T{
S
T}:T{
s
T}:T{
2
T}:T{
2
T}:T{
3
T}:T{
20(24)
T}
T{
輸送艦 (Troop Transport)
T}:T{
T
T}:T{
t
T}:T{
2
T}:T{
1
T}:T{
1
T}:T{
30(36)
T}
T{
空母 (Aircraft Carrier)
T}:T{
C
T}:T{
c
T}:T{
2
T}:T{
8
T}:T{
1
T}:T{
30(36)
T}
T{
戦艦 (Battleship)
T}:T{
B
T}:T{
b
T}:T{
2
T}:T{
10
T}:T{
2
T}:T{
40(48)
T}
T{
人工衛星 (Satellite)
T}:T{
Z
T}:T{
z
T}:T{
10
T}:T{
\-\-
T}:T{
\-\-
T}:T{
50(60)
T}
.TE
.sp 1
.PP
2列目はマップ上のあなたのユニットを表しています。
.PP
3列目は敵のユニットを表しています。
.PP
移動(Moves)はそのユニットが1ラウンドで移動できるマスの数です。
.PP
ヒットポイント(Hits)は破壊に必要なダメージの量です。
.PP
攻撃(Str)は各ラウンドの攻撃で与えるダメージの量です。
.PP
コスト(Cost)は都市でそのユニットを生成するまでに必要なラウンド数です。
.PP
カッコ内の数値はその都市で最初のユニットを生成するまでのコストです。
.PP
ユニットにはそれぞれ特徴があります。 このゲームの戦略上の重要な問題の1つは、どのユニットをどれだけ生成すべきかです。
.PP
\fB地上部隊(Army)\fRは陸のみを移動できる、そして陸のみを移動する唯一のユニットです。 地上部隊のみが都市を占領できます。 つまり、ゲームに勝つためには地上部隊を生成しなければなりません。 地上部隊は都市を攻撃したとき、50%の確率で占領することができます。 (自分の都市を攻撃すると地上部隊は破壊されます。 地上部隊は海に入るとおぼれてしまいます。 地上部隊は海のユニットを攻撃できますが、たとえ勝利してもおぼれます。) 地上部隊は輸送艦で運ぶことができます。 地上部隊が輸送艦の上に移動したならば、輸送艦が移動すると、地上部隊も輸送艦と一緒に移動します。 輸送されている間は、地上部隊は海上のユニットを攻撃できません。
.PP
\fB戦闘機(Fighter)\fRは陸と海の両方を移動でき、そして1ラウンドで8マス移動できます。 高速性と優れた移動力を持つ戦闘機は探索に適しています。 しかし、戦闘機は定期的に自分の都市に着地して燃料を補充しなければなりません。 戦闘機は補給なしで32マス移動することができます。 また、戦闘機は自分のものでない都市を通過しようとすると撃墜されてしまいます。
.PP
\fB哨戒艇(Patrol boat)\fRは高速ですが軽武装の艦船です。 よって、このユニットは海の哨戒と探索に適しています。 しかし、より強い艦船と戦うと、哨戒艇は大きな打撃を受けるでしょう。
.PP
\fB駆逐艦(Destroyers)\fRはやや重武装で、比較的早く生産できる艦船です。 よって、世界中に広がろうとする敵の輸送艦を破壊するのに適しています。
.PP
\fB潜水艦(Submarine)\fRの攻撃が命中すると、1ではなく3のヒットポイントを奪えます。 よって、潜水艦は重武装した敵の艦船に大打撃を与えることができます。 無傷の潜水艦は無傷の駆逐艦を2/3の確率で破壊できることに注目してください。 しかし、潜水艦が戦闘機を破壊できる確率は2/3ですが、駆逐艦は戦闘機を3/4の確率で破壊できます。
.PP
\fB輸送艦(Troop transport)\fRは地上部隊を運べる唯一のユニットです。 1ユニットの輸送艦で最大6ユニットの地上部隊を運ぶことができます。 海の多い世界では、輸送はゲームの勝敗を決める重要な問題となります。 輸送艦は弱く、より強い艦船で護衛する必要があるので注意してください。
.PP
\fB空母(Aircraft carrier)\fRは戦闘機を運べる唯一の艦船です。 空母は残りヒットポイントの数だけ戦闘機を運ぶことができます。 戦闘機は空母に着艦すると燃料が補充されます。
.PP
\fB戦艦(Battleship)\fRはより強力であることを除けば駆逐艦と同じです。
.PP
\fB人工衛星(Satellite)\fRは探索しかできません。 人工衛星は攻撃されません。 人工衛星はランダムな角度に打ち上げられ、50ターン活動します。 人工衛星は他のユニットより1マス広く探索できます。
.PP
全ての艦船ユニットは海上のみ移動できます。 艦船は自分の都市に入港することもできます。 入港すると1ターンにつき1ヒットポイントのダメージを回復できます。 艦船は大ダメージを受けると移動が遅くなります。
.PP
この回復能力があるため、空母や戦艦のようなヒットポイントの多い艦船は有利です。 敵の艦船を破壊する途中で受けたダメージが小さいならば、これらの艦船は都市に戻り、敵が破壊された艦船を補充する時間を与えずにすばやく回復することができます。
.PP
次の表は、戦闘で横のユニットが縦のユニットに勝利する確率を示しています。 (両者ともダメージを受けていないと仮定します。)
.TS
allbox center tab(:);
c l c c c c
l c c c c c
l c c c c c
l c c c c c
l c c c c c
l c c c c c.
T{
\ \&
T}:T{
AFPT
T}:T{
D
T}:T{
S
T}:T{
C
T}:T{
B
T}
T{
AFPT
T}:T{
50\&.0%
T}:T{
12\&.5%
T}:T{
25\&.0%
T}:T{
00\&.391%
T}:T{
00\&.0977%
T}
T{
D
T}:T{
87\&.5%
T}:T{
50\&.0%
T}:T{
25\&.0%
T}:T{
05\&.47%
T}:T{
00\&.537%
T}
T{
S
T}:T{
75\&.0%
T}:T{
75\&.0%
T}:T{
50\&.0%
T}:T{
31\&.3%
T}:T{
06\&.25%
T}
T{
C
T}:T{
99\&.6%
T}:T{
94\&.5%
T}:T{
68\&.7%
T}:T{
50\&.0%
T}:T{
04\&.61%
T}
T{
B
T}:T{
99\&.9%
T}:T{
99\&.5%
T}:T{
93\&.8%
T}:T{
95\&.4%
T}:T{
50\&.0%
T}
.TE
.sp 1
.PP
しかし、艦船がダメージを受けている場合は、この確率が変化するので注意してください。 例えば、無傷の潜水艦は1のダメージを受けた戦艦に25%の確率で勝利でき、無傷の潜水艦は2のダメージを受けた空母に50%の確率で勝利できます。
.SH "任務"
.PP
任務(function)には様々なものが存在します。 ユニットの任務はユーザモードとエディットモードで設定できます。 都市にユニットごとの任務を設定することもできます。 都市にユニットの種類ごとの任務を設定すると、都市で新しいユニットが生産されるたびにユニットに任務が設定されます。 輸送中の輸送艦や、戦闘機を載せた空母が都市に入ると、望まない副作用があるので注意してください。
.PP
通常、一度任務を設定すると、ユニットは次のことが発生するまでその任務に従って行動し続けます:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
移動先に敵のユニットまたは占領していない都市があるとき。 この場合、指定の方向への移動以外は、ユニットの任務は完全に解除されます。 輸送中の地上部隊と都市内のユニットは、もし行動するときに敵のユニットがいなくなっていれば、任務は解除されません。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
あなたが任務の解除を指示したとき。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
そのユニットが任務された行動を続けられないとき。 この場合、そのユニットは\fI一時的に\fR任務が解除され、ユニットの移動方向を尋ねられます。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
戦闘機ユニットの燃料が最も近い都市に移動できる最小(と少しの余裕)の量になったとき。 この場合、移動先を指示するか、\fI着地(Land)\fRを指示するまでユニットの任務は解除された状態になります。
.RE
.PP
この複雑さの背後にある考え方は、戦闘機の任務の解除を忘れて墜落する前に、完全に任務を解除されなければならないというものです。 しかし、戦闘機の方向が設定されると、その戦闘機は燃料切れの危険がないとみなしています。
.PP
移動方向が設定されたユニットは、方向がリセットされてしまうのは無駄であるため、任務は完全に解除されません。 しかし、解除することは簡単です(キーを1回押す)。
.PP
任務には次のものがあります:
.PP
\fB攻撃(Attack)\fR
.RS 4
この任務は地上部隊のみ可能です。 この任務が設定されると、地上部隊は最も近い敵の都市、中立の都市、または敵の地上部隊に向かって移動します。 これは進攻する敵を撃退する場合や、新しい領土を獲得する場合に便利です。 この任務が設定された地上部隊は、近くの領域の探索も行います。 そのため、「探索(grope)」任務はあまり使う機会がありません。
.RE
.PP
\fB解除(Awake)\fR
.RS 4
任務が解除されると、ユニットは毎ターン方向を尋ねてきます。
.RE
.PP
\fB搭載(Fill)\fR
.RS 4
この任務は空母と輸送艦に対して可能です。 この任務が設定されると、艦船が戦闘機または地上部隊でいっぱいになるまで留まります。
.RE
.PP
\fB探索(Grope)\fR
.RS 4
この任務はユニットに探索させます。 ユニットはそれぞれマップ上の最も近い未探索の区域へ向かいます。 統計的に最適な探索を行うためのいくつかの試みが行われています。
.RE
.PP
\fB着地(Land)\fR
.RS 4
この戦闘機への任務は、戦闘機を最も近い都市か空母へと向かわせます。
.RE
.PP
\fBランダム(Random)\fR
.RS 4
この任務はユニットを隣の空いたマスへランダムに移動させます。
.RE
.PP
\fB防衛(Sentry)\fR
.RS 4
この任務はユニットを静止させます。 都市上ではこの任務で「静止」させることはできません。
.RE
.PP
\fB搭乗(Transport)\fR
.RS 4
この任務は地上部隊のみ可能です。 地上部隊は近くを満杯でない輸送艦が来るまで静止し、輸送艦が来ると地上部隊は動き出し輸送艦に乗ります。
.RE
.PP
\fB修理(Upgrade)\fR
.RS 4
この任務は艦船のみ可能です。 艦船は最も近い自分の都市へ移動し、修理されるまで待ちます。
.RE
.PP
\fB<方向>\fR
.RS 4
ユニットの移動方向を設定します。
.RE
.PP
\fB<目的地>\fR
.RS 4
ユニットを指定の場所へ移動させさせます。 この移動モードでは、ユニットは目的地へ最短の経路で移動します。 この任務を設定されたユニットは斜めに進んで探索することが多くなります。 そのため、ユニットの移動は直感に反するかもしれません。
.RE
.PP
任務の使い方の一例は、新しい大陸の都市を獲得したとき、その都市の地上部隊の任務を\fI攻撃\fRにすることです。 地上部隊が生産されるたびに、次々と大陸を探索し、まだ手に入れていない都市や敵の地上部隊や都市に向かって移動します。
.PP
都市の艦船の任務は、遠くにある都市から前線に艦船を自動的に移動させるためによく設定されます。
.PP
大陸に地上部隊がいても探索や攻撃の対象がないときは、海辺まで移動させ、\fI搭乗\fR任務を設定し、輸送艦が通過したとき乗るようにします。
.SH "コマンド"
.PP
3つのコマンドモードがあります。 1つ目は「コマンドモード」です。 このモードはゲーム全体に影響を与えます。 2つ目のモード「移動モード」はあなたのユニットに命令を与えます。 3つ目のモードは「エディットモード」で、ユニットの任務を編集や、マップの様々な場所を見ることができます。
.PP
全てのコマンドの長さは1文字です。 覚えられるように完全な命令名の一覧が下にあります。 命令名には不自然なものもありますが、それは英語のアルファベットが少ないためです。 このプログラムが日本語で書かれていないのが残念ですね?
.PP
全てのコマンドモードで、"H"を押すとヘルプが表示され、<ctrl\-L>を押すと画面が再描画されます。
.SH "コマンドモード"
.PP
コマンドモードでは、コンピュータはあなたの命令を待ちます。 このとき次のコマンドを受け付けます:
.PP
\fBAutomove(移動モード)\fR
.RS 4
移動モードへ移行します。 このコマンドで新しいラウンドが始まります。 コンピュータのターンの後も移動モードが継続されます。 (移動モードでは、"O"コマンドでコンピュータのターンが終わった後でコマンドモードに戻ります。)
.RE
.PP
\fBCity(都市)\fR
.RS 4
コンピュータにランダムな中立都市を与えます。 このコマンドはコンピュータが弱すぎると思ったときに便利です。
.RE
.PP
\fBDate(日時)\fR
.RS 4
現在のラウンドを表示します。
.RE
.PP
\fBExamine(調査)\fR
.RS 4
敵のマップを調査します。 このコマンドはコンピュータが降伏した後にのみ有効です。
.RE
.PP
\fBFile(ファイル)\fR
.RS 4
マップを指定したファイルに書き込みます。
.RE
.PP
\fBGive(与える)\fR
.RS 4
このコマンドはコンピュータに手番を与えます。
.RE
.PP
\fBJ\fR
.RS 4
エディットモードへ移行し、調査やあなたのユニットや都市の任務を変更できるようにします。
.RE
.PP
\fBMove(チェンジ)\fR
.RS 4
1ラウンドだけ移動モードへ移行します。
.RE
.PP
\fBN\fR
.RS 4
コンピュータに指定した回数の手番を与えます。
.RE
.PP
\fBPrint(表示)\fR
.RS 4
セクターを画面に表示します。
.RE
.PP
\fBQuit(終了)\fR
.RS 4
ゲームを終了します。
.RE
.PP
\fBRestore(復帰)\fR
.RS 4
empsave\&.datからゲームを復帰させます。
.RE
.PP
\fBSave(保存)\fR
.RS 4
ゲームをempsave\&.datに保存します。
.RE
.PP
\fBTrace(トレース)\fR
.RS 4
このコマンドはフラグをセットします。 フラグがセットされていると、あなたとコンピュータの手番の後、ゲームの状態が\*(Aqempmovie\&.dat\*(Aqファイルに書き込まれます。
\fB注意! このコマンドはたくさんのファイルを生成します。\fR
.RE
.PP
\fBWatch(観戦)\fR
.RS 4
このコマンドは保存された棋譜を再生します。 棋譜は1画面に収まるように縮小されているため、再生はやや分かりにくいものになります。 このコマンドはコンピュータが降伏した後にのみ有効です。 あなたが負けた場合は、棋譜を再生してコンピュータがあなたを打ち負かした秘密を知ることはできません。 また、再生でコンピュータのユニットの現在の位置を知ることもできません。 棋譜の再生中は、\fB\-d\fRオプションで遅延時間を2000ミリ秒程度に設定することを薦めます。 そうしないと画面の更新が早すぎて何が起こっているかわからないでしょう。
.RE
.PP
\fBZoom(ズーム)\fR
.RS 4
画面に縮小されたマップを表示します。 マップはいくつもの小さな長方形に区切られます。 これらの長方形は画面上で1つのマスとして表示されます。 もし長方形内に都市があればそれが表示されます。 そうでなければ、敵のユニットがあれば表示され、次はあなたのユニット、陸、海、未探索の領域の順で表示されます。 ユニットは艦船が戦闘機や陸上部隊より優先されて表示されます。
.RE
.SH "移動モード"
.PP
移動モードでは、画面上の移動が必要な各ユニット上にカーソルが現れます。 その後、ユニットに移動コマンドを与えられるようになります。 移動の方向は次のキーで指定します:
.sp
.if n \{\
.RS 4
.\}
.nf
\fI
        QWE
        A D
        ZXC
\fR
.fi
.if n \{\
.RE
.\}
.PP
あなたの端末にカーソルキーとテンキーがあればそれも有効のはずです。
.PP
これらのキーは、Sキーから見た方向へ移動させます。 これらの文字はエコーせず、また1文字のみ受け付けます。 よって<リターン>の必要はありません。 その場にとどまりたい場合は<スペース>バーを押してください。
.PP
他のコマンドは:
.PP
\fBBuild(構築)\fR
.RS 4
都市の生産を変更します。
.RE
.PP
\fBFill(搭載)\fR
.RS 4
輸送艦または空母の任務を\fI搭載\fRに設定します。
.RE
.PP
\fBGrope(探索)\fR
.RS 4
ユニットの任務を\fI探索\fRに設定します。
.RE
.PP
\fBI\fR\fI方向\fR
.RS 4
ユニットの移動方向を設定します。
.RE
.PP
\fBJ\fR
.RS 4
エディットモードへ移行します。
.RE
.PP
\fBKill(解除)\fR
.RS 4
ユニットの任務を解除します。 もしそのユニットが輸送艦または空母ならば、搭載されたユニットの任務は解除されません。
.RE
.PP
\fBLand(着地)\fR
.RS 4
戦闘機の任務を\fI着地\fRに設定します。
.RE
.PP
\fBOut(戻る)\fR
.RS 4
移動モードを中断します。 ラウンドが終わるとコマンドモードになります。
.RE
.PP
\fBPrint(表示)\fR
.RS 4
画面を再描画する。
.RE
.PP
\fBRandom(ランダム)\fR
.RS 4
ユニットの任務を\fIランダム\fRに設定します。
.RE
.PP
\fBSentry(防衛)\fR
.RS 4
ユニットの任務を\fI防衛\fRに設定します。
.RE
.PP
\fBTransport(搭乗)\fR
.RS 4
地上部隊の任務を\fI搭乗\fRに設定します。
.RE
.PP
\fBUpgrade(修理)\fR
.RS 4
艦船の任務を\fI修理\fRに設定します。
.RE
.PP
\fBV\fR\fIユニット 任務\fR
.RS 4
都市にユニットの任務を設定します。 例えば、"VAY"と入力すると、都市の地上部隊の任務は\fI攻撃\fRになります。 この都市で地上部隊が生産されると(または地上部隊を乗せた輸送艦が都市に入ると)、地上部隊の任務が\fI攻撃\fRに設定されます。
.RE
.PP
\fBY\fR
.RS 4
地上部隊の任務を\fI攻撃\fRに設定します。
.RE
.PP
\fB?\fR
.RS 4
ユニットの情報を表示します。 任務、残りヒットポイント、燃料、輸送中のユニット数が表示されます。
.RE
.PP
攻撃は攻撃したい相手のマスに移動することで行います。 ヒット率は50%で、攻撃した側とされた側が交互にどちらかが完全に破壊されるまで行います。 勝者はどちらか一方のみです。
.PP
味方の都市やユニットへの攻撃など\fB致命的な\fR行為も「許可」されています。 致命的な行為を行おうとすると、コンピュータは警告しやり直す機会を与えます。
.PP
マップの端へ移動することはできません。
.SH "エディットモード"
.PP
エディットモードでは、世界中を見渡し、ユニットを調べ、新しい任務を設定することができます。 カーソルは通常の方向キーで動かせます。 他のコマンドは:
.PP
\fBBuild(構築)\fR
.RS 4
カーソルを合わせた都市の生産を変えます。 プログラムは新しい生産を尋ねるので、生産したいユニットの文字のキーを押して答えます。
.RE
.PP
\fBFill(搭載)\fR
.RS 4
輸送艦または空母の任務を\fI搭載\fRに設定します。
.RE
.PP
\fBGrope(探索)\fR
.RS 4
ユニットの任務を\fI探索\fRに設定します。
.RE
.PP
\fBI\fR\fI方向\fR
.RS 4
ユニット(または都市)の方向を設定します。
.RE
.PP
\fBKill(解除)\fR
.RS 4
その場の全てのユニットの任務を解除します。 もしその場所が都市ならば、戦闘機の航路も解除されます。
.RE
.PP
\fBMark(選択)\fR
.RS 4
現在の場所のユニットまたは都市を選択します。 このコマンドは"N"コマンドと一緒に使います。
.RE
.PP
\fBN\fR
.RS 4
"M"コマンドで選択したユニットの目的地を現在の場所に設定します。
.RE
.PP
\fBOut(戻る)\fR
.RS 4
エディットモードを終了します。
.RE
.PP
\fBPrint(表示)\fR\fIセクター\fR
.RS 4
セクターのマップを新たに表示します。 マップは20マス\(mu70マスの10のセクターに分かれています。 セクター0がマップの左上、セクター4がマップの左下、セクター5が右上、そしてセクター9が右下です。
.RE
.PP
\fBRandom(ランダム)\fR
.RS 4
ユニットがランダムに移動するようにします。
.RE
.PP
\fBSentry(防衛)\fR
.RS 4
ユニットが動かないようにします。
.RE
.PP
\fBTransport(搭乗)\fR
.RS 4
地上部隊の任務を\fI搭乗\fRに設定します。
.RE
.PP
\fBUpgrade(修理)\fR
.RS 4
艦船の任務を\fI修理\fRに設定します。
.RE
.PP
\fBV\fR\fIユニット 任務\fR
.RS 4
都市にユニットの任務を設定します。
.RE
.PP
\fBY\fR
.RS 4
地上部隊の任務を\fI攻撃\fRに設定します。
.RE
.PP
\fB?\fR
.RS 4
ユニットまたは都市の情報を表示します。 都市ならば、生産、次のユニットが完成するまでの時間、任務、そしてその都市の戦闘機と艦船の数が表示されます。
.RE
.PP
エディットモードでは都市内のユニットに直接影響を与えられないので注意してください。
.SH "ヒント"
.PP
このゲームでしばらく遊ぶと、コンピュータに簡単に勝てることがわかるでしょう。 このゲームをより面白くするいくつかのアイデアがあります。
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ゲームが始まる前にコンピュータに1つかそれ以上の都市を与える。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
滑らかさの値を小さくする(\-s2 か、さらに \-s0 オプションを試してみる)。
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ゲームを始めると、難易度を尋ねられます。 この「難易度」は必ずしも正しくありません。 プログラムは陸地と陸地の都市の数で難易度を決めています。 高「難易度」では、コンピュータに広い陸地と多くの都市が与えられ、ユーザには小さな陸地と少ない都市が与えられます。 低「難易度」はその逆になります。 「難易度」が低い場合の方がコンピュータがうまくプレーする場合もあります。 その理由は、この場合コンピュータはゲームの初期の段階で複数の陸地に地上部隊を展開することを強制されるためです。
.RE
.SH "歴史"
.PP
\m[blue]\fBA Brief History of Empire\fR\m[]\&\s-2\u[1]\d\s+2によると、このゲームの原型は1970年代初頭にカリフォルニア工科大学の学生Walter Brightによって作られました。 コピーが大学から流出し、1979年秋頃にTOPS\-10/20 FORTRANのソースコードが使えるDECのVAX/VMSに移植されました。 1983年にCraig LeresはDECUSのテープからソースコードを発見し、様々な種類の端末に対応させました。
.PP
Ed Jamesはバークレーでソースコードを手に入れ、C言語に移植し、画面の操作の大半でcursesを使用するようにしました。 1986年12月、彼は自分が修正したソースコードをネットで公開しました。 このゲームは長い間VMSマシンで動いていたためVMS Empireとして知られています。
.PP
1987年、アムダール社のChuck Simmonsはプログラムを解析し、完全なC言語版を作成しました。 その過程で、彼はコンピュータの戦略、コマンド、ユニットの種類、多くのユニットの特性、そしてマップ生成のアルゴリズムを修正しました。
.PP
このゲームの様々なバージョンは、後のCivilization (1990)やMaster of Orion (1993)などの4Xゲーム(expand/explore/exploit/exterminate)(探索/拡張/利用/排除)の原型となりました。
.PP
1994年、Eric Raymondはこのゲームをカラー化しました。
.SH "ファイル"
.PP
\fIempsave\&.dat\fR
.RS 4
ゲームのバックアップが保存されています。 empireが実行されると、このファイルにゲームの状態が次々と書き込まれます。
.RE
.PP
\fIempmovie\&.dat\fR
.RS 4
ゲームの履歴が保存され、「棋譜」として再生できるようになります。
.RE
.SH "バグ"
.PP
間違いなく無数にあります。
.PP
保存ファイルはバージョン1\&.13以降は互換性がなくなっています。
.PP
人工衛星は完全には実装されていません。 人工衛星のあるマスには移動できるべきですが、それはできません。 敵の人工衛星はあなたのユニットの任務を解除しません。
.SH "作者"
.PP
このゲームの原作者はWalter Brightです。 Craig Leresは様々な種類の端末に対応させました。 Ed Jamesはcursesに対応させました。 Chuck SimmonsはC/Unix版を作成しました。 Eric S\&. Raymondはカラーに対応させました。 Michael Selfは確率表を訂正しました。
.SH "COPYLEFT"
.PP
Copyright (C) 1987, 1988 Chuck Simmons
.PP
See the file COPYING, distributed with empire, for restriction and warranty information\&.
.SH "NOTES"
.IP " 1." 4
A Brief History of Empire
.RS 4
\%http://www.classicempire.com/history.html
.RE
